/**
* Generated by LEA for Arma 3
* Version: 2.0.22
* Tue Jan 20 18:40:25 EST 2015
* Mission file name: COP_Keating2.Altis
* Mission name: COP_Keating2.Altis
* Required mods:
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutMultiplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//Empty, nothing to do. unit unit_24_146
//Empty, nothing to do. unit unit_24_147
//Empty, nothing to do. unit unit_24_148
//Empty, nothing to do. unit unit_24_149
//Empty, nothing to do. unit unit_24_150
//Empty, nothing to do. unit unit_24_151
//Empty, nothing to do. unit unit_24_152
//Empty, nothing to do. unit unit_24_153
//Empty, nothing to do. unit unit_39_198

/**
* Loadout for soldiers units
*/

if (!isNil "unit_37_196") then {
	if (player == unit_37_196) exitwith {

if (count weapons unit_37_196 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons unit_37_196) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     unit_37_196 selectWeapon (_muzzles select 0);
  }
  else {
     unit_37_196 selectWeapon _type;
  };
};
	};
};

